config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  resources :patients
  resources :doctors
  root 'static_pages#home'

  get  'about'   => 'static_pages#about'

  get  'contact' => 'static_pages#contact'

  get  'help'    => 'static_pages#help'

  get  'signup'  => 'users#new'

  resources :users

  resources :receptionists
  resources :nurses
  resources :accountants
  resources :pharmacists

end

app/models/accountant.rb
class Accountant < ActiveRecord::Base
end

app/controllers/accountants_controller.rb
class AccountantsController < ApplicationController
  before_action :set_accountant, only: [:show, :edit, :update, :destroy]

  # GET /accountants
  # GET /accountants.json
  def index
    @accountants = Accountant.all
  end

  # GET /accountants/1
  # GET /accountants/1.json
  def show
  end

  # GET /accountants/new
  def new
    @accountant = Accountant.new
  end

  # GET /accountants/1/edit
  def edit
  end

  # POST /accountants
  # POST /accountants.json
  def create
    @accountant = Accountant.new(accountant_params)

    respond_to do |format|
      if @accountant.save
        format.html { redirect_to @accountant, notice: 'Accountant was successfully created.' }
        format.json { render :show, status: :created, location: @accountant }
      else
        format.html { render :new }
        format.json { render json: @accountant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accountants/1
  # PATCH/PUT /accountants/1.json
  def update
    respond_to do |format|
      if @accountant.update(accountant_params)
        format.html { redirect_to @accountant, notice: 'Accountant was successfully updated.' }
        format.json { render :show, status: :ok, location: @accountant }
      else
        format.html { render :edit }
        format.json { render json: @accountant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accountants/1
  # DELETE /accountants/1.json
  def destroy
    @accountant.destroy
    respond_to do |format|
      format.html { redirect_to accountants_url, notice: 'Accountant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accountant
      @accountant = Accountant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accountant_params
      params.fetch(:accountant, {})
    end
end

app/controllers/admin/accountant_controller.rb
class Admin::AccountantController < ApplicationController
end

app/helpers/accountants_helper.rb
module AccountantsHelper
end

app/helpers/admin/accountant_helper.rb
module Admin::AccountantHelper
end

app/views/accountants/_form.html.erb
<%= form_for(@accountant) do |f| %>
  <% if @accountant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accountant.errors.count, "error") %> prohibited this accountant from being saved:</h2>

      <ul>
      <% @accountant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accountants/edit.html.erb
<h1>Editing Accountant</h1>

<%= render 'form' %>

<%= link_to 'Show', @accountant %> |
<%= link_to 'Back', accountants_path %>

app/views/accountants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accountants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accountants.each do |accountant| %>
      <tr>
        <td><%= link_to 'Show', accountant %></td>
        <td><%= link_to 'Edit', edit_accountant_path(accountant) %></td>
        <td><%= link_to 'Destroy', accountant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accountant', new_accountant_path %>

app/views/accountants/new.html.erb
<h1>New Accountant</h1>

<%= render 'form' %>

<%= link_to 'Back', accountants_path %>

app/views/accountants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_accountant_path(@accountant) %> |
<%= link_to 'Back', accountants_path %>