config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  resources :patients
  resources :doctors
  root 'static_pages#home'

  get  'about'   => 'static_pages#about'

  get  'contact' => 'static_pages#contact'

  get  'help'    => 'static_pages#help'

  get  'signup'  => 'users#new'

  resources :users

  resources :receptionists
  resources :nurses
  resources :accountants
  resources :pharmacists

end

app/models/pharmacist.rb
class Pharmacist < ActiveRecord::Base
end

app/controllers/admin/pharmacist_controller.rb
class Admin::PharmacistController < ApplicationController
end

app/controllers/pharmacists_controller.rb
class PharmacistsController < ApplicationController
  before_action :set_pharmacist, only: [:show, :edit, :update, :destroy]

  # GET /pharmacists
  # GET /pharmacists.json
  def index
    @pharmacists = Pharmacist.all
  end

  # GET /pharmacists/1
  # GET /pharmacists/1.json
  def show
  end

  # GET /pharmacists/new
  def new
    @pharmacist = Pharmacist.new
  end

  # GET /pharmacists/1/edit
  def edit
  end

  # POST /pharmacists
  # POST /pharmacists.json
  def create
    @pharmacist = Pharmacist.new(pharmacist_params)

    respond_to do |format|
      if @pharmacist.save
        format.html { redirect_to @pharmacist, notice: 'Pharmacist was successfully created.' }
        format.json { render :show, status: :created, location: @pharmacist }
      else
        format.html { render :new }
        format.json { render json: @pharmacist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pharmacists/1
  # PATCH/PUT /pharmacists/1.json
  def update
    respond_to do |format|
      if @pharmacist.update(pharmacist_params)
        format.html { redirect_to @pharmacist, notice: 'Pharmacist was successfully updated.' }
        format.json { render :show, status: :ok, location: @pharmacist }
      else
        format.html { render :edit }
        format.json { render json: @pharmacist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharmacists/1
  # DELETE /pharmacists/1.json
  def destroy
    @pharmacist.destroy
    respond_to do |format|
      format.html { redirect_to pharmacists_url, notice: 'Pharmacist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharmacist
      @pharmacist = Pharmacist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharmacist_params
      params.fetch(:pharmacist, {})
    end
end

app/helpers/admin/pharmacist_helper.rb
module Admin::PharmacistHelper
end

app/helpers/pharmacists_helper.rb
module PharmacistsHelper
end

app/views/pharmacists/_form.html.erb
<%= form_for(@pharmacist) do |f| %>
  <% if @pharmacist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pharmacist.errors.count, "error") %> prohibited this pharmacist from being saved:</h2>

      <ul>
      <% @pharmacist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pharmacists/edit.html.erb
<h1>Editing Pharmacist</h1>

<%= render 'form' %>

<%= link_to 'Show', @pharmacist %> |
<%= link_to 'Back', pharmacists_path %>

app/views/pharmacists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pharmacists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pharmacists.each do |pharmacist| %>
      <tr>
        <td><%= link_to 'Show', pharmacist %></td>
        <td><%= link_to 'Edit', edit_pharmacist_path(pharmacist) %></td>
        <td><%= link_to 'Destroy', pharmacist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pharmacist', new_pharmacist_path %>

app/views/pharmacists/new.html.erb
<h1>New Pharmacist</h1>

<%= render 'form' %>

<%= link_to 'Back', pharmacists_path %>

app/views/pharmacists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pharmacist_path(@pharmacist) %> |
<%= link_to 'Back', pharmacists_path %>